- id: doi:10.1021/acsami.4c17502
  image: images/Papers/2025Megareview.JPG
  tags:
  - SERS
  - Review
  - GERTs
  - TRS

- id: doi:10.1021/acsami.4c20139
  title: Single-Injection Composite Tracer Achieves Intraoperative Dual-Tracing and
    Precise Localization of Sentinel Lymph Nodes
  image: images/Papers/2025ACS AMI.jpg
  authors:
  - Binge Deng
  - <strong>Linley Li Lin*</strong>
  - Yan Wang
  - Xiangdong Bu
  - Jin Li
  - Jingsong Lu
  - Yaohui Wang*
  - Yao Chen*
  - Jian Ye*
  tags:
   - SERS
   - GERTs
   - NIR-II
   - Sentinel lymph node detection
   - Non-human primates
  
- id: doi:10.1021/acsnano.4c12469
  title: In Vivo Surface-Enhanced Transmission Raman Spectroscopy and Impact of Frozen Biological Tissues on Lesion Depth Prediction
  image: images/Papers/2024ACS Nano.png
  authors:
  - Yutong Zhou
  - Yumin Zhang
  - Haoqiang Xie
  - Zongyu Wu
  - Bowen Shi
  - <strong>Linley Li Lin*</strong>
  - Jian Ye*
  tags:
    - Transmission Raman spectroscopy
    - Tissue optical properties
    - Depth estimation
  
- id: doi:10.1016/j.saa.2024.124852
  image: images/Papers/2024SAA3.JPG
  authors:
  - Yuqing Gu
  - Siyi Wu
  - Zhewen Luo
  - <strong>Linley Li Lin*</strong>
  - Jian Ye*
  tags:
  - SERS
  - Metabolite detection
  - Liquid biopsy 
  
- id: doi:10.1007/s00216-024-05545-w
  image: images/Papers/2024ABC.jpg
  authors:
  - Shiyan Fang
  - Pei Xu
  - Siyi Wu
  - Zhou Chen
  - Junqing Yang
  - Haibo Xiao
  - Fangbao Ding
  - Shuchun Li
  - Jin Sun
  - Zirui He*
  - Jian Ye*
  - <strong>Linley Li Lin*</strong>
  tags:
    - Raman diagnosis
    - Gastric tumor
    - EDRS
    - Euclidean distance-based Raman spectroscopy
  
- id: doi:10.3390/bios14080372
  image: images/Papers/2024Biosensors.JPG
  tags:
    - Raman diagnosis
    - Thyroid tumor
    - Liquid biopsy
  authors:
  - Lili Gao
  - Siyi Wu
  - Puwasit Wongwasuratthakul
  - Zhou Chen
  - Wei Cai
  - Qinyu Li
  - <strong>Linley Li Lin</strong>
  
- id: doi:10.1016/j.saa.2024.125062 
  image: images/Papers/2024SAA2.JPG
  tags:
    - Raman diagnosis
    - Gastric tumor
    - EDRS
    - Euclidean distance-based Raman spectroscopy
  authors:
  - Bowen Shi#
  - Wenfang Wang#
  - Shiyan Fang#
  - Siyi Wu
  - Lan Zhu
  - Yong Chen
  - Haipeng Dong
  - Fuhua Yan
  - Fei Yuan
  - Jian Ye*
  - Huan Zhang*
  - <strong>Linley Li Lin*</strong>
  
- id: doi:10.1016/j.biomaterials.2024.122538
  image: images/Papers/2024Biomaterials.jpg
  authors: Binge Deng, Yan Wang, Xiangdong Bu, Jin Li, Jingsong Lu, <strong>Linley Li Lin*</strong>, Yaohui Wang*, Yao Chen*, Jian Ye*
  tags:
    - NIR-II
    - GERTs
    - Sentinel lymph node detection
    - Non-human primates
    
- id: doi:10.1002/smll.202402235
  image: images/Papers/review.JPG
  authors: Binge Deng, Yuqing Zhang, Guangyu Qiu, Jin Li, <strong>Linley Li Lin*</strong>, Jian Ye*
  tags:
    - NIR-II 
    - SERS

- id: doi:10.1016/j.saa.2024.124461
  image: images/Papers/2024SAA.jpg
  authors: Junqing Yang , Pei Xu, Siyi Wu, Zhou Chen, Shiyan Fang, Haibo Xiao, Fengqing Hu, Lianyong Jiang , Lei Wang, Bin Mo, Fangbao Ding*, <strong>Linley Li Lin*</strong>, Jian Ye*
  date: '2024-05-11'
  tags:
    - Raman disnosis
    - Esophageal tumor
    
- id: doi:10.1016/j.trac.2024.117578
  image: images/Papers/review.JPG
  authors: Shiyan Fang, Siyi Wu, Zhou Chen, Chang He, <strong>Linley Li Lin*</strong>, Jian Ye*
  tags:
    - AI
    - Spectral denoising
    - Raman
    
- id: doi:10.1002/smtd.202301243
  image: images/Papers/review.JPG
  authors: Xinyuan Bi, <strong>Li Lin</strong>, Zhou Chen*, Jian Ye*
  tags:
    - SERS
    - AI
    
- id: doi:10.1021/acsami.3c07792
  image: images/Papers/2023ACSAMI.jpg
  authors: Haoqiang Xie, Yumin Zhang, Zongyu Wu, Zhouzhou Bao*, <strong>Li Lin*</strong>, Jian Ye*
  tags:
    - Transmission Raman spectroscopy
    - Tomography
    - GERTs

- id: doi:10.1007/s44258-023-00010-2
  type: paper
  description: We report the use of surface-enhanced Raman scattering nanotags embedded in ex-vivo animal tissues for direct and quantitative measurements of light attenuation and spectroscopic detection depth at both the NIR-I and NIR-II spectral windows.
  date: '2023-08-14'
  authors: <strong>Li Lin*</strong>, Haoqi He, Ruiyang Xue, Yumin Zhang, Ziwen Wang, Shuming Nie*, Jian Ye*
  image: images/Papers/MEDX2023.jpg
  tags:
    - SERS
    - Detection depth assessment
    - Second near-infrared window
    - NIR-II
    - GERTs
    
- id: doi:10.1002/advs.202301721
  image: images/Papers/AS2023.jpg
  authors: Zongyu Wu, Binge Deng*, Yutong Zhou, Haoqiang Xie, Yumin Zhang, <strong>Li Lin*</strong>, Jian Ye*
  tags: 
    - Transmission Raman spectroscopy
    - Noninvasive in vivo detection
      
- id: doi:10.1002/viw.20230022
  image: images/Papers/View.jpg
  authors: Yumin Zhang, <strong>Li Lin*</strong>, Jian Ye*
  tags: 
    - Transmission Raman spectroscopy
    - Depth estimation

- id: doi:10.1016/j.saa.2022.122163
  image: images/Papers/SAPA-2023.jpg
  authors: Wenfang Wang, Bowen Shi, Chang He, Siyi Wu, Lan Zhu, Jiang Jiang, Lingyun Wang, <strong>Li Lin*</strong>, Jian Ye*, Huan Zhang*
  tags:
    - Euclidean distance-based Raman spectroscopy
    - EDRS
    - Gastric cancer prognosis

- id: doi:10.1002/smtd.202201334 
  image: images/Papers/Smallmethods-2023.jpg
  authors:
   - Yumin Zhang
   - Ruoyu Chen
   - Peng Miao
   - <strong>Li Lin*</strong>
   - Jian Ye*
  tags: 
    - Transmission Raman spectroscopy
    - Ultrahigh detection depth in biological tissues

- id: doi:10.1016/b978-0-12-822425-0.00111-1
  image: images/Papers/3-s2.0-C20190035649-cov200h.gif
  tags:
    - Book chapter
    - SERS Nanoparticle
    - Encyclopedia of Nanomaterials

- id: doi:10.1021/acs.jpcc.2c02512
  image: images/Papers/JPCC-2022.jpg
  authors: Haoqi He, Shuo Zhu, Yumin Zhang, Jian Ye*, <strong>Li Lin*</strong>
  tags:
    - Second near-infrared window
    - NIR-II
    - SERS tag
    - Au nanorod

- id: doi:10.3390/photonics9060429
  authors: Zongyu Wu, Ziwen Wang, Haoqiang Xie, Yiming Wang, Haoqi He, Shuming Nie, Jian Ye, <strong>Li Lin*</strong>
  image: images/Papers/Photonics-2022.jpg
  tags:
    - Bronchoscopy
    - Lung Tissue
    - GERTs
    
- id: doi:10.1016/j.apsusc.2019.05.200  
  tags:
    - GERTs
    
- id: doi:10.1021/acsami.2c01063
  authors: Shuo Zhu, Binge Deng, Fugang Liu, Jin Li, <strong>Li Lin</strong>, Jian Ye*
  image: images/Papers/2022ACSAMI.JPG
  tags:
    - Au nanorod
    - SERS
    
- id: doi:10.1038/s41467-019-14070-9
  image: images/Papers/2020NC.jpg
  tags:
    - GERTs
    
- id: doi:10.7150/thno.39968    
  image: images/Papers/review.JPG
  tags:
    - Review
    - SERS Nanoparticle
    - GERTs


- id: doi:10.1016/j.mtbio.2022.100205
  authors: Yao Lu, <strong>Li Lin*</strong>, Jian Ye*
  image: images/Papers/review.JPG
  tags:
    - SERS
    - Metabolite detection

# Before 2021

- id: doi:10.1063/5.0047578 
  authors: Li Lin, Xinyuan Bi, Yuqing Gu, Fu Wang, Jian Ye*
  image: images/Papers/review.JPG
  tags:
    - review
    - SERS

- id: doi:10.1142/S1793545821410017
  authors: Yumin Zhang#, <Li Lin#, Jing He, Jian Ye*
  image: images/Papers/JIOHS-2021.jpg
  tags:
    - Au nanorod
    - SERS
    - detection depth assessment
   
    
- id: doi:10.1021/acs.jpcc.0c09552
  authors: Li Lin, Weiming Ji, Lu-Wen Zhang*, Jian Ye*
  image: images/Papers/JPCC-2021.JPG
  tags:
    - Molecular dynamics
    - GERTs
    - Plasmonic junction


- id: doi:10.1002/smtd.201800182
  image: images/Papers/2018SM.jpg
  tags:
    - Internal standard
    - GERTs


- id: doi:10.1021/acsami.6b15170
  image: images/Papers/2017ACSAMI.jpeg
  tags:
    - GERTs
    - Photostability

    
- id: doi:10.1039/c6nr08501f
  image: images/Papers/Nanoscale-2017.jpg
  tags:
     - GERTs
     - Plasmonic junction
     
- id: doi:10.1021/acsnano.7b08224
  image: images/Papers/ACSNano-2018.png
  tags:
    - SERS
    - GERTs
    - Plasmonic junction

- id: doi:10.1021/acs.nanolett.5b02931
  image: images/Papers/nanolett-2015.jpg
  tags:
    - SERS
    - GERTs
    - Plasmonic junction

- id: doi:10.1039/c5cc06599b
  image: images/Papers/CC-2015.jpg
  tags:
    - SERS
    - GERTs
    - Plasmonic junction



    


   
